//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResSocet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResSocet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarehouseResource.ResSocet", typeof(ResSocet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj gniazdo.
        /// </summary>
        public static string AddSocet {
            get {
                return ResourceManager.GetString("AddSocet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymiary gniazda.
        /// </summary>
        public static string DemensionsSocet {
            get {
                return ResourceManager.GetString("DemensionsSocet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolna przestrzeń.
        /// </summary>
        public static string FreeVolume {
            get {
                return ResourceManager.GetString("FreeVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit wagi.
        /// </summary>
        public static string FreeWeight {
            get {
                return ResourceManager.GetString("FreeWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna wysokość.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identyfikator gniazda.
        /// </summary>
        public static string InfoSocet {
            get {
                return ResourceManager.GetString("InfoSocet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna dlugość.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista gniazd magazynowych.
        /// </summary>
        public static string ListSocet {
            get {
                return ResourceManager.GetString("ListSocet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna objętość.
        /// </summary>
        public static string MaxVolume {
            get {
                return ResourceManager.GetString("MaxVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalne obciążenie.
        /// </summary>
        public static string MaxWeight {
            get {
                return ResourceManager.GetString("MaxWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie ma gniazda magazynowego dla podanego kodu.
        /// </summary>
        public static string NoSocetToBarcode {
            get {
                return ResourceManager.GetString("NoSocetToBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rząd regału.
        /// </summary>
        public static string RowBookstand {
            get {
                return ResourceManager.GetString("RowBookstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Półka regału.
        /// </summary>
        public static string ShelfBookstand {
            get {
                return ResourceManager.GetString("ShelfBookstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gniazdo magazynowe.
        /// </summary>
        public static string Socet {
            get {
                return ResourceManager.GetString("Socet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer gniazda.
        /// </summary>
        public static string SocetNumber {
            get {
                return ResourceManager.GetString("SocetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykorzystana objętość.
        /// </summary>
        public static string UseVolume {
            get {
                return ResourceManager.GetString("UseVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykorzystane obciążenie.
        /// </summary>
        public static string UseWeight {
            get {
                return ResourceManager.GetString("UseWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna szerokość.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
